package hasync

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/BrianTillman/Denmother/internal/project"
	"github.com/BrianTillman/Denmother/internal/util"

	"github.com/fatih/color"
)

// SyncResult holds the results of a sync operation
type SyncResult struct {
	EntitiesCount  int
	DevicesCount   int
	AreasCount     int
	EntityListPath string
	DeviceListPath string
	AreaListPath   string
	Entities       map[string]bool // Entity IDs for mismatch analysis
	Warnings       []string
}

// Syncer handles syncing entities from Home Assistant
type Syncer struct {
	client     *Client
	configPath string
	quiet      bool
}

// NewSyncer creates a new Syncer
func NewSyncer(haURL, haToken, configPath string) *Syncer {
	return &Syncer{
		client:     NewClient(haURL, haToken),
		configPath: configPath,
	}
}

// SetQuiet enables/disables quiet mode
func (s *Syncer) SetQuiet(quiet bool) {
	s.quiet = quiet
}

// SyncAll syncs entities, devices, and areas from Home Assistant
func (s *Syncer) SyncAll() (*SyncResult, error) {
	result := &SyncResult{}

	settings, err := project.ForConfig(s.configPath)
	if err != nil {
		return nil, err
	}
	refDir := settings.ReferencesDir
	if err := os.MkdirAll(refDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create reference directory: %w", err)
	}

	if !s.quiet {
		color.Cyan("Checking Home Assistant connectivity...")
	}
	if err := s.client.Ping(); err != nil {
		return nil, fmt.Errorf("cannot connect to Home Assistant: %w", err)
	}
	if !s.quiet {
		color.Green("  Connected to Home Assistant")
	}

	if !s.quiet {
		color.Cyan("\nFetching entities...")
	}
	entities, err := s.client.FetchEntities()
	if err != nil {
		return nil, err
	}
	result.EntitiesCount = len(entities)
	if !s.quiet {
		color.Green("  Fetched %d entities", len(entities))
	}

	result.Entities = make(map[string]bool, len(entities))
	for _, e := range entities {
		result.Entities[e.EntityID] = true
	}

	entityListPath := filepath.Join(refDir, "entity-list.txt")
	if err := s.saveEntityList(entities, entityListPath); err != nil {
		return nil, err
	}
	result.EntityListPath = entityListPath

	if !s.quiet {
		color.Cyan("\nFetching devices and areas...")
	}
	devices, areas, err := s.client.FetchDevicesAndAreas()
	if err != nil {
		result.Warnings = append(result.Warnings, fmt.Sprintf("device/area fetch was partial: %v", err))
		if !s.quiet {
			color.Yellow("  Warning: %v", err)
		}
	}

	// A non-nil slice is a successful fetch, including an empty registry.
	if devices != nil {
		result.DevicesCount = len(devices)
		if !s.quiet {
			color.Green("  Fetched %d devices", len(devices))
		}

		deviceListPath := filepath.Join(refDir, "device-list.txt")
		if err := s.saveDeviceList(devices, deviceListPath); err != nil {
			return nil, err
		}
		result.DeviceListPath = deviceListPath
	}

	// Failed datasets remain nil and retain their previous snapshot with a warning.
	if areas != nil {
		result.AreasCount = len(areas)
		if !s.quiet {
			color.Green("  Fetched %d areas", len(areas))
		}

		areaListPath := filepath.Join(refDir, "area-list.txt")
		if err := s.saveAreaList(areas, areaListPath); err != nil {
			return nil, err
		}
		result.AreaListPath = areaListPath
	}

	return result, nil
}

// SyncEntities syncs only entities from Home Assistant
func (s *Syncer) SyncEntities() (int, string, error) {
	settings, err := project.ForConfig(s.configPath)
	if err != nil {
		return 0, "", err
	}
	refDir := settings.ReferencesDir
	if err := os.MkdirAll(refDir, 0755); err != nil {
		return 0, "", fmt.Errorf("failed to create reference directory: %w", err)
	}

	entities, err := s.client.FetchEntities()
	if err != nil {
		return 0, "", err
	}

	entityListPath := filepath.Join(refDir, "entity-list.txt")
	if err := s.saveEntityList(entities, entityListPath); err != nil {
		return 0, "", err
	}

	return len(entities), entityListPath, nil
}

func (s *Syncer) saveEntityList(entities []EntityState, path string) error {
	entityIDs := make([]string, 0, len(entities))
	for _, e := range entities {
		entityIDs = append(entityIDs, e.EntityID)
	}
	sort.Strings(entityIDs)

	var buffer bytes.Buffer
	writer := bufio.NewWriter(&buffer)
	fmt.Fprintf(writer, "# Current Home Assistant Entities\n")
	fmt.Fprintf(writer, "# Generated: %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(writer, "# Total entities: %d\n", len(entityIDs))
	fmt.Fprintf(writer, "# This file was automatically generated by dm sync\n")
	fmt.Fprintln(writer)

	for _, id := range entityIDs {
		fmt.Fprintln(writer, id)
	}

	if err := writer.Flush(); err != nil {
		return fmt.Errorf("failed to write entity list: %w", err)
	}
	if err := util.WriteFileAtomic(path, buffer.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to publish entity list: %w", err)
	}

	if !s.quiet {
		color.Green("  Saved entity list to: %s", path)
	}
	return nil
}

func (s *Syncer) saveDeviceList(devices []Device, path string) error {
	sort.Slice(devices, func(i, j int) bool {
		return devices[i].Name < devices[j].Name
	})

	var buffer bytes.Buffer
	writer := bufio.NewWriter(&buffer)
	fmt.Fprintf(writer, "# Live Devices from Home Assistant API\n")
	fmt.Fprintf(writer, "# Generated: %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(writer, "# Total devices: %d\n", len(devices))
	fmt.Fprintln(writer)

	for _, d := range devices {
		identifier := ""
		if len(d.Identifiers) > 0 && len(d.Identifiers[0]) > 1 {
			identifier = d.Identifiers[0][1]
		}
		fmt.Fprintf(writer, "%s: %s (%s)\n", d.ID, d.Name, identifier)
	}

	if err := writer.Flush(); err != nil {
		return fmt.Errorf("failed to write device list: %w", err)
	}
	if err := util.WriteFileAtomic(path, buffer.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to publish device list: %w", err)
	}

	if !s.quiet {
		color.Green("  Saved device list to: %s", path)
	}
	return nil
}

func (s *Syncer) saveAreaList(areas []Area, path string) error {
	sort.Slice(areas, func(i, j int) bool {
		return areas[i].Name < areas[j].Name
	})

	var buffer bytes.Buffer
	writer := bufio.NewWriter(&buffer)
	fmt.Fprintf(writer, "# Live Areas from Home Assistant API\n")
	fmt.Fprintf(writer, "# Generated: %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(writer, "# Total areas: %d\n", len(areas))
	fmt.Fprintln(writer)

	for _, a := range areas {
		fmt.Fprintf(writer, "%s: %s\n", a.AreaID, a.Name)
	}

	if err := writer.Flush(); err != nil {
		return fmt.Errorf("failed to write area list: %w", err)
	}
	if err := util.WriteFileAtomic(path, buffer.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to publish area list: %w", err)
	}

	if !s.quiet {
		color.Green("  Saved area list to: %s", path)
	}
	return nil
}

// LoadEntityList loads entities from the entity-list.txt file
func LoadEntityList(configPath string) (map[string]bool, error) {
	settings, err := project.ForConfig(configPath)
	if err != nil {
		return nil, err
	}
	path := filepath.Join(settings.ReferencesDir, "entity-list.txt")
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	entities := make(map[string]bool)
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		entities[line] = true
	}

	return entities, scanner.Err()
}

// OrphanedDevice represents a device with no associated entities
type OrphanedDevice struct {
	Device       Device
	EntityCount  int
	HasEmptyName bool
}

// OrphanResult holds the results of orphan detection
type OrphanResult struct {
	TotalDevices    int
	OrphanedDevices []OrphanedDevice
	ReportPath      string
}

// FindOrphanedDevices identifies devices that have no associated entities
func (s *Syncer) FindOrphanedDevices() (*OrphanResult, error) {
	if !s.quiet {
		color.Cyan("\nAnalyzing devices for orphans...")
	}

	wsClient := NewWSClient(s.client.baseURL, s.client.token)
	if err := wsClient.Connect(); err != nil {
		return nil, fmt.Errorf("failed to connect WebSocket: %w", err)
	}
	defer wsClient.Close()

	devices, err := wsClient.FetchDevicesWS()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch devices: %w", err)
	}
	if !s.quiet {
		color.Green("  Fetched %d devices", len(devices))
	}

	entityRegistry, err := wsClient.FetchEntityRegistryWS()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch entity registry: %w", err)
	}
	if !s.quiet {
		color.Green("  Fetched %d entity registry entries", len(entityRegistry))
	}

	deviceEntityCount := make(map[string]int)
	for _, entry := range entityRegistry {
		if entry.DeviceID != "" {
			deviceEntityCount[entry.DeviceID]++
		}
	}

	var orphaned []OrphanedDevice
	for _, device := range devices {
		count := deviceEntityCount[device.ID]
		if count == 0 {
			orphaned = append(orphaned, OrphanedDevice{
				Device:       device,
				EntityCount:  0,
				HasEmptyName: strings.TrimSpace(device.Name) == "",
			})
		}
	}

	if !s.quiet {
		color.Yellow("  Found %d orphaned devices (no entities)", len(orphaned))
	}

	sort.Slice(orphaned, func(i, j int) bool {
		if orphaned[i].HasEmptyName != orphaned[j].HasEmptyName {
			return orphaned[i].HasEmptyName
		}
		return orphaned[i].Device.Name < orphaned[j].Device.Name
	})

	settings, err := project.ForConfig(s.configPath)
	if err != nil {
		return nil, err
	}
	refDir := settings.ReferencesDir
	if err := os.MkdirAll(refDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create reference directory: %w", err)
	}

	reportPath := filepath.Join(refDir, "orphaned-devices.txt")
	if err := s.saveOrphanReport(orphaned, len(devices), reportPath); err != nil {
		return nil, err
	}

	return &OrphanResult{
		TotalDevices:    len(devices),
		OrphanedDevices: orphaned,
		ReportPath:      reportPath,
	}, nil
}

func (s *Syncer) saveOrphanReport(orphaned []OrphanedDevice, totalDevices int, path string) error {
	var buffer bytes.Buffer
	writer := bufio.NewWriter(&buffer)
	fmt.Fprintf(writer, "# Orphaned Devices Report\n")
	fmt.Fprintf(writer, "# Generated: %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(writer, "# Total devices: %d\n", totalDevices)
	fmt.Fprintf(writer, "# Orphaned (no entities): %d\n", len(orphaned))
	fmt.Fprintln(writer)

	emptyNameCount := 0
	for _, o := range orphaned {
		if o.HasEmptyName {
			emptyNameCount++
		}
	}

	if emptyNameCount > 0 {
		fmt.Fprintf(writer, "## Devices with empty names (%d) - likely stale registry entries:\n\n", emptyNameCount)
		for _, o := range orphaned {
			if o.HasEmptyName {
				info := formatDeviceInfo(o.Device)
				fmt.Fprintf(writer, "%s: (no name) %s\n", o.Device.ID, info)
			}
		}
		fmt.Fprintln(writer)
	}

	namedCount := len(orphaned) - emptyNameCount
	if namedCount > 0 {
		fmt.Fprintf(writer, "## Named devices with no entities (%d) - investigate before deleting:\n\n", namedCount)
		for _, o := range orphaned {
			if !o.HasEmptyName {
				info := formatDeviceInfo(o.Device)
				fmt.Fprintf(writer, "%s: %s %s\n", o.Device.ID, o.Device.Name, info)
			}
		}
	}

	if err := writer.Flush(); err != nil {
		return fmt.Errorf("failed to write orphan report: %w", err)
	}
	if err := util.WriteFileAtomic(path, buffer.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to publish orphan report: %w", err)
	}

	if !s.quiet {
		color.Green("  Saved orphan report to: %s", path)
	}
	return nil
}

func formatDeviceInfo(d Device) string {
	var parts []string
	if d.Manufacturer != "" || d.Model != "" {
		parts = append(parts, fmt.Sprintf("(%s %s)", d.Manufacturer, d.Model))
	}
	if len(d.ConfigEntries) > 0 {
		parts = append(parts, fmt.Sprintf("[integrations: %s]", strings.Join(d.ConfigEntries, ", ")))
	}
	if d.AreaID != "" {
		parts = append(parts, fmt.Sprintf("area: %s", d.AreaID))
	}
	if d.DisabledBy != "" {
		parts = append(parts, fmt.Sprintf("disabled: %s", d.DisabledBy))
	}
	return strings.Join(parts, " ")
}
